### ISSUE TITLE
wwt assertion failed with GC ISOs

### ISSUE THREAD

**Issue by nilp0inter** [Wiimm/wiimms-iso-tools#1]
Hi,

I am hitting this assert trying to add a GC ISO.

https://github.com/Wiimm/wiimms-iso-tools/blob/24e2650dea3a994dc3c8149646eb80bc6a8b291a/project/src/libwbfs/wiidisc.c#L865

```
wwt add --ignore --auto /home/nil/Downloads/Super\ Mario\ Sunshine.iso
*****  wwt: Wiimms WBFS Tool v3.02a r0 x86_64 - Dirk Clemens - 2020-07-31  *****
WBFSv1 #1/1 opened: /dev/sdb
 - ADD 1/1 [GMSP01] ISO:/home/nil/Downloads/Super Mario Sunshine.iso
!! wwt: ERROR #126 [FATAL ERROR] in wd_read_part() @ src/libwbfs/wiidisc.c#865
!!      ASSERTION FAILED !!!
```

Any ideas?

**Comment by nilp0inter** [comment]
I've just commented the assert and tried again.  This time the ISO was copied successfully and the resulting game although listed OK by `wwt list` coudn't be run through USB Loader GX (it is listed with an empty name and when run it just reset the USB Loader).

**Comment by Wiimm** [comment]
I removed the assertion already in my working copy anyone in the past. So it is fixed. I plan a new release soon.
