### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by Soundtoxin** [Wiimm/wiimms-iso-tools#2]
What license is this software intended to use?

https://choosealicense.com/

**Comment by teapot9** [comment]
This project is licensed under GPL-2.0, see [project/gpl-2.0.txt](https://github.com/Wiimm/wiimms-iso-tools/blob/fb217fb75b4f449dd00ecbeeae7a35082e87218c/project/gpl-2.0.txt).

**Comment by Soundtoxin** [comment]
That's good to hear, but the standard way I've seen is to have a file
called "LICENSE" or "COPYING" in the top level project directory. If
done right, GitHub should also clearly display the license used over on
the side of the page. It makes it easy to tell at a glance.

Here's a project where it shows: https://github.com/jarun/Buku

**Comment by teapot9** [comment]
Fair enough, it will improve the project's visibility on Github.
But at this point, it might as well be a good idea to set a project description and add some keywords.
